# Generated by Django 4.1.3 on 2022-11-14 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
