# Generated by Django 4.1.3 on 2022-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
