# Generated by Django 4.1.3 on 2022-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
